[tool.black]
exclude = '''
(
  /(
      .git
    | .env
    | .venv
    | env
    | venv
    | requirements
    | templates
    | tests
  )/
)
'''

[tool.isort]
profile = "black"
src_paths = ["./"]
skip = [
    ".git",
    ".env",
    ".venv",
    "env",
    "venv",
    "requirements",
    "templates",
]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

#[tool.pylint."MASTER"]
#ignore = [
#    ".git",
#    ".env",
#    ".venv",
#    "env",
#    "venv",
#    "requirements",
#    "templates",
#    "tests",
#]
#
#[tool.pylint."MESSAGES CONTROL"]
#disable = [
#  "too-many-arguments",
#]